
" Source normal vimrc
if filereadable(expand("~/.vimrc"))
	source ~/.vimrc
endif

set antialias
"colorscheme nuvola
colorscheme elflord
set guifont=Monospace\ 8


autocmd BufRead *.as set filetype=actionscript
autocmd BufRead *.mxml set filetype=actionscript

" ,/ C/C++/C#/Java // comments
map ,c :s/^/\/\/ /<CR>
map ,C :s.^// .. <CR> :noh <CR>

" # comments
map ,s :s/^/# /<CR>
map ,S :s.^# .. <CR> :noh <CR>

